### PR TITLE
Let smooth be optional for cornerplot

### PR DESCRIPTION
**Pull request by mauro3**
This is probably not how it is done properly, but it works.  Trying out the dirty-hack strategy again ;-)

### CODE REVIEW

**Comment by tbreloff** [comment]
Can't you just change ':=' to '-->'?

**Comment by mauro3** [comment]
I tried a few iterations of that but it didn't seem to work. you mean on line https://github.com/JuliaPlots/StatPlots.jl/blob/master/src/cornerplot.jl#L100 , right?

**Comment by tbreloff** [comment]
Right

**Comment by tbreloff** [comment]
f34ff30

**Pull request closed without merging**
