### PR TITLE
Better outliers for boxplots

### PR DESCRIPTION
**Pull request by diegozea**
This PR adds and `outliers` keyword argument. If `outliers=false`,  the outliers are not drawn (similar to R's boxplot `outline`).

It also allows to change outlier shape and color.

Best,

### CODE REVIEW

**Comment by mkborregaard** [comment]
Nice. One thing I dream of doing is to add an argument that adds different styles to boxplots - implemented as different patterns of line thickness among box, whiskers and central (median) bar.

**Comment by mkborregaard** [comment]
I'm ready to merge this, if it's ready.

**Comment by diegozea** [comment]
Hi @mkborregaard ! I found a estrange bug with the Recipe, because `markershape --> :circle` creates outliers without shape. So, I need to force the shape using `markershape := :circle`. Do you have any hint on what is going on?

**Comment by mkborregaard** [comment]
No but I'll take a look.

**Comment by diegozea** [comment]
I also tried the following in the boxplot recipe and It didn't work:
`linecolor --> d[:markerstrokecolor]`. However, using `:=` instead of `-->` works as expected.

**Comment by diegozea** [comment]
I found the problem. `:markershape` is already `:none`, then `get!(d,:markershape,:circle)` or (`markershape --> :circle`)  can't change that.

**Comment by mkborregaard** [comment]
where do you get the :none?

**Comment by diegozea** [comment]
I get the `markershape` `:none` printing `d` just before the line `seriestype := :shape`.

**Comment by diegozea** [comment]
Ok! It's ready to merge! :smiley: 

In the las commit I added also a `whisker_width` keyword argument to modify the width of the whisker end. Set `whisker_width=0` to get whiskers similar to *R's ggplot* whiskers.

`linecolor` is set as `markerstrokecolor` (`foregroud_color`) if it is identical to the `fillcolor` (in order to se the median line).

Outliers' shape and alpha are free, but colors are identical to the corresponding box.

#### Example:
```julia
using StatPlots; const x = rand(50); x[1:3] = 2:4; const y = rand(50); y[1:3] = 2:4; const X = [1 2]; const Y = hcat(x,y);

plot(boxplot(X,Y), boxplot(X,Y,linecolor=:orange), boxplot(X,Y,outliers=false), boxplot(X,Y,whisker_width=0))

```
image

**Comment by mkborregaard** [comment]
Nice work, I like the whisker_width arg as well (but horrible to spell right). I think @tbreloff mentioned to me that he had a specific reason for having the linecolor as it is, so I will just give him a chance to comment before merging :-)

**Comment by tbreloff** [comment]
LGTM

**Comment by diegozea** [comment]
Great, thanks! :)

**Comment by mkborregaard** [comment]
Great, thanks a lot!

**Comment by mkborregaard** [comment]
Just a comment: on the plots above, it is clear that x and y axis width inference goes awry when outliers are suppressed. The x axis must be different for `Shape` and `scatter`. This could be an issue in Plots, rather than here. @pkofod any good guesses?

**Comment by pkofod** [comment]
@diegozea this was already merged, so frugter changes should be in a separate pr

**Comment by mkborregaard** [comment]
But I think this has roots in Plots, not this PR.

**Comment by pkofod** [comment]
> But I think this has roots in Plots, not this PR.

I was just referring to the fact that it was merged 11 hours ago, and there seems to have been added commits 10 hours ago.

**Comment by pkofod** [comment]
wait.. it says "10 hours from now", haha.. time travel programming 
hoursfromnow

**Comment by mkborregaard** [comment]
It looks strange here on github, yes, but I did merge it after those commits :-)

**Comment by mkborregaard** [comment]
Ahh, "10 hours from now", haha.

**Pull request merged**
