### PR TITLE
replace d by plotattributes inside recipes

### PR DESCRIPTION
**Pull request by jw3126**
See https://github.com/JuliaPlots/Plots.jl/issues/1107

### CODE REVIEW

**Comment by jw3126** [comment]
Yeah, I already signed up.

**Comment by mkborregaard** [comment]
Can you rebase?

**Comment by jw3126** [comment]
Sure!

**Comment by mkborregaard** [comment]
Sorry, could you do an actual rebase rather than merging master into your branch? This will make the git branching look fishy. Sorry for being particular about this.

**Comment by jw3126** [comment]
Yeah I just pressed this shiny button on github. I will do this properly later.

**Comment by jw3126** [comment]
Done!

**Comment by mkborregaard** [comment]
Thanks!

**Pull request merged**
